### ISSUE TITLE
Guild Channels in Guild Object

### ISSUE THREAD

**Issue by Eanae** [weibeu/Flask-Discord#17]
Any plans to populate the Guild object with a list of channels?

**Comment by thec0sm0s** [comment]
@A-Trash-Coder is working on bot endpoint resources like that. I think then we will try covering most of the bot enpoints as well.

**Comment by Eanae** [comment]
Yeah looking to use this for a Discord bot and wanted to resolve channel IDs to names in channel selection fields. I don't want to store user data to know what channels are what IDs. That'd be perfect if it was done.

**Comment by kramrm** [comment]
This would be helpful as I am building a web dashboard to manage a bot's config.

**Comment by thec0sm0s** [comment]
Thanks for reminding me. This will be my next TODO.

**Comment by weibeu** [comment]
Have made a separate issue: #45 to track feature requests related to or based on bot resources. So will close this and please use the new issue for further discussion related to this.
