### ISSUE TITLE
(invalid_request) Invalid "code" in request.

### ISSUE THREAD

**Issue by Wallvon** [weibeu/Flask-Discord#26]
Hi there,

I currently have an application running with Flask-Discord, but when users try to log in they sometimes get stuck at /callback with `(invalid_request) Invalid "code" in request.` or `Not enough segments`. Is there any way to fix this? Please let me know!

Thanks,
Robert S.

**Comment by thec0sm0s** [comment]
Got this same issue from others as well. I tried but I couldn't reproduce this on my own. Is there any specific flow which produces this issue? Also not sure if this thing might be related: https://github.com/jpadilla/pyjwt/issues/405

**Comment by alexfrunza** [comment]
I think i know what's the issue, but i don't know how to explain better if you are on a dev server on your localhost and your `DISCORD_REDIRECT_URI` looks like this `'http://127.0.0.1:5000/callback'` you must be all time on `'http://127.0.0.1:5000` not on `http://localhost:5000/` address, that was the fix for me

**Comment by Wallvon** [comment]
> 
> 
> I think I know what's the issue, but I don't know how to explain better, if you are on a dev server on your localhost and your `DISCORD_REDIRECT_URI` looks like this `'http://127.0.0.1:5000/callback'` you must be all time on `'http://127.0.0.1:5000` not on `http://localhost:5000/` address, that was the fix for me

Yeah, my script doesn't automatically add a `/`, so that shouldn't be the problem. I have no idea how to reproduce it though, but I do have Sentry installed so I can quickly look at the errors. The `Not enough segments` error occurs on `/callback` and it gives a `ValueError: not enough values to unpack (expected 2, got 1)`. The codes indeed look a little short, and here is an image with where it struggles. It happens at random, but it does happen quite a lot (I got 1.5k of these events).
![afbeelding](https://user-images.githubusercontent.com/42699143/92935192-bf264380-f448-11ea-9664-01cc87228d1c.png)

About the `(invalid_request) Invalid "code" in request.`, that happens at random (I got 1.1k of these events), and maybe this image helps.
![afbeelding](https://user-images.githubusercontent.com/42699143/92935429-0f050a80-f449-11ea-91dc-970421c677cd.png)

**Comment by thec0sm0s** [comment]
I tried reproducing the above exceptions. 
![image](https://user-images.githubusercontent.com/34530901/93050398-72c54880-f680-11ea-9cc1-9de8dc161443.png)

So the error `(invalid_request) Invalid "code" in request` indicates that it could be someone else making false requests to your callback endpoint. You can reproduce it by passing invalid `code` in params to your callback endpoint.

However, the exception `jwt.exceptions.DecodeError: Not enough segments` tells that Discord auth grant was completed successfully but somehow (could be many reasons) that the state passed by Discord to your callback endpoint is invalid.

Let me know your comments on this.

**Comment by yonderbread** [comment]
Having the same issue too, I get a 500 error after authorization, but I do get a code in the url but it seems that the callback uri isn't valid or something.

**Comment by thec0sm0s** [comment]
This exception can also be reproduced by trying to login through say `http://127.0.0.1/login/` but you have `http://localhost/callback/` configured as your callback URL set or vice-versa.
So yeah this won't work since cookies set as state before login was for the URL 127.0.0.1 but after calling, this exact same cookie isn't available in localhost. **So use either 127.0.0.1 or localhost.**

![image](https://user-images.githubusercontent.com/34530901/93161747-d73fe080-f730-11ea-88d6-b8c0618ddbf9.png)
![image](https://user-images.githubusercontent.com/34530901/93161751-d8710d80-f730-11ea-971a-cdea48f651fb.png)

(The first screenshot was taking after clicking the "login" button and cookie get issue to localhost. But when I get callback to 127.0.0.1 this cookie doesn't exists at all.)

**Comment by thec0sm0s** [comment]
@Wallvon A possible patch has been applied and pushed to PyPI. Update your package and let us know how it goes. I hope you might not get those JWT Decode Error after this.

**Comment by pieckenst** [comment]
The `raise DecodeError("Not enough segments") from err` is still occuring even in current version of flask discord

**Comment by weibeu** [comment]
@pieckenst Can you get me your pyjwt version. You can use command `pip show pyjwt`.

**Comment by pieckenst** [comment]
> 
> 
> @pieckenst Can you get me your pyjwt version. You can use command `pip show pyjwt`.
`PS H:\canary\helia\src> pip show pyjwt
Name: PyJWT
Version: 2.1.0
Summary: JSON Web Token implementation in Python
Home-page: https://github.com/jpadilla/pyjwt
Author: Jose Padilla
Author-email: hello@jpadilla.com
License: MIT
Location: c:\program files\python39\lib\site-packages
Requires:
Required-by: Flask-Discord
PS H:\canary\helia\src>`

**Comment by weibeu** [comment]
@pieckenst Just making sure, have you checked this case https://github.com/weibeu/Flask-Discord/issues/26#issuecomment-692439451

**Comment by pieckenst** [comment]
> 
> 
> @pieckenst Just making sure, have you checked this case [#26 (comment)](https://github.com/weibeu/Flask-Discord/issues/26#issuecomment-692439451)

![4SKp5wHk9X](https://user-images.githubusercontent.com/46422808/116664874-b8314e80-a9a1-11eb-97ef-8df84815db22.png)
![4rtaB12rDT](https://user-images.githubusercontent.com/46422808/116664878-b9627b80-a9a1-11eb-8237-c028065cf38f.png)
cookies seem to be stored fine on both?

**Comment by weibeu** [comment]
What I mean is that you should either decide to use localhost or 127.0.0.1. And the one you choose to use, use the same hostname in your callback endpoint also.
For example if you're using localhost, then you need to set your callback URL something like `http://localhost/callback` including in app configuration and in Discord developers dashbaord.

**Comment by pieckenst** [comment]
> 
> 
> What I mean is that you should either decide to use localhost or 127.0.0.1. And the one you choose to use, use the same hostname in your callback endpoint also.
> For example if you're using localhost, then you need to set your callback URL something like `http://localhost/callback` including in app configuration and in Discord developers dashbaord.

K got it , and im currently at least having it set to 127.0.0.1
