### ISSUE TITLE
Include list of keys used from configs in documentation.

### ISSUE THREAD

**Issue by weibeu** [weibeu/Flask-Discord#29]
Flask-Discord makes use of the Flask config for few configurations values like Discord application client ID, secret, etc. and more. However, the documentation is missing list and description about all of the keys used by the library.

Describing them in the documentation might be helpful to the library users to better fine tune it as for their needs.

Quick way to find them is to look for `config["` in the project files.

**Comment by HarryET** [comment]
https://github.com/thec0sm0s/Flask-Discord/pull/31
