### ISSUE TITLE
Add guild object

### ISSUE THREAD

**Issue by kimjunsung04** [weibeu/Flask-Discord#30]
Currently, the guilds object exists, but the guild object does not exist, so it is not possible to get a lot of information, such as the number of server personnel.  I think you need to add guild object.

**Comment by thec0sm0s** [comment]
These resources are provided **outside of OAuth2** which uses bot's token. So yeah work is in progress for things you mentioned.

**Comment by kimjunsung04** [comment]
당신의 프로젝트를 응원합니다.  시간이 걸리더라도 언젠가 업데이트를 기다릴 것입니다.

**Comment by weibeu** [comment]
Have made a separate issue: #45 to track feature requests related to or based on bot resources. So will close this and please use the new issue for further discussion related to this.
