### ISSUE TITLE
Upgrade to Discord API V8

### ISSUE THREAD

**Issue by nighthawki** [weibeu/Flask-Discord#41]
It would be great if you could update to the newest discord api version v8.

**Comment by weibeu** [comment]
Thanks for reminding, will do this by weekend.

**Comment by VeNoMouS** [comment]
Whats the status of this?

**Comment by weibeu** [comment]
Apologies, got along with some other stuffs. Will make sure to put this on priority and attempt to do this soon within next few weeks.

**Comment by VeNoMouS** [comment]
> Apologies, got along with some other stuffs. Will make sure to put this on priority and attempt to do this soon within next few weeks.

cheers

**Comment by VeNoMouS** [comment]
lol the code base hasnt been touched in over 2 years... alot of us have dumped this project in favor of others that are maintained
