### ISSUE TITLE
How does one get the user ID if they are overriding save_authorization_token?

### ISSUE THREAD

**Issue by FM1337** [weibeu/Flask-Discord#50]
I'm trying to handle token storing server side, I nearly got everything working but I need to have access to the user's ID but I cannot seem to obtain it using the `fetch_user()` method, even if I set the token in session momentarily before calling it. What magic can I do to get around this issue?

**Comment by jnawk** [comment]
why not just use a session driver that doesn't write the content of the session to a cookie?

**Comment by FM1337** [comment]
> why not just use a session driver that doesn't write the content of the session to a cookie?

So using something like https://flask-session.readthedocs.io/en/latest/ is what you're suggesting?

**Comment by jnawk** [comment]
> > why not just use a session driver that doesn't write the content of the session to a cookie?
> 
> So using something like https://flask-session.readthedocs.io/en/latest/ is what you're suggesting?

yes exactly.  you'll need to pick a backend, your choice will be guided by what scale your app runs at - a single server, you could use memory or disk, multiple servers, you'll want to use a database or cache

**Comment by FM1337** [comment]
> > > why not just use a session driver that doesn't write the content of the session to a cookie?
> > 
> > 
> > So using something like https://flask-session.readthedocs.io/en/latest/ is what you're suggesting?
> 
> yes exactly. you'll need to pick a backend, your choice will be guided by what scale your app runs at - a single server, you could use memory or disk, multiple servers, you'll want to use a database or cache

Thanks, got it working
