### ISSUE TITLE
Implement Email scope

### ISSUE THREAD

**Issue by FabiChan99** [weibeu/Flask-Discord#57]
Hey, i would ask if it is possible to add Support to get a users Email?

**Comment by weibeu** [comment]
The scopes which are used by default includes email. So you should be able to get user email after they authorize your application and auth grant is completed.

**Comment by FabiChan99** [comment]
But how will i get the users email? I dont find anything in the library

**Comment by weibeu** [comment]
Take a look at me() function in example here: https://flask-discord.readthedocs.io/en/latest/introduction.html#basic-usage

As they used `user.name`, similarly you can do `user.email` to get users email.
