### ISSUE TITLE
Package dependencies are too strict

### ISSUE THREAD

**Issue by henriquegemignani** [weibeu/Flask-Discord#58]
In 0985cb26d902aaf201561b0878d0febf5fc4d4d2 the `install_requires` of the package was updated to require specific versions of all dependencies, recursively.

For testing this package itself, locking that way is great. But for downstream packages this at best prevents me from updating any of these packages, at worst causes conflicts with other packages.

**Comment by jnawk** [comment]
the only package with a version requirement is an inequality  - `"pyjwt>=2.0.0"` - versions earlier than 2.0 are not compatible and are a source of endless bug tickets, the solution to each of course is update `pyjwt`.

**Comment by weibeu** [comment]
Thanks for pointing it out! Have released the dependencies from exact versions and set it only where it was needed (for PyJWT). Have updated PyPI.
