### ISSUE TITLE
does the example bot work with locahost?

### ISSUE THREAD

**Issue by anishp55** [weibeu/Flask-Discord#59]
i am using your example, and have updated it with my tokens etc to get started.
whenever i access the the page via localhost or its local ip, i get Invalid oAuth2 redirect_uri

does this uri need to be publicly accessible for this example to work?

**Comment by weibeu** [comment]
Can you verify and check if you're setting redirect URL in your Discord application developers dashboard something like this:
![image](https://user-images.githubusercontent.com/34530901/155684581-b949c439-bf7e-488f-9a3b-bd22277b2f8f.png)

**Comment by anishp55** [comment]
hello,  yes sorry i figured this out last night after posting and forgot to close this.  thank you.
